// Generates docs/CATALOG.md (and docs/catalog.json): everything implemented in the atlas, read from the built page itself.
// Run: node build.mjs && npm run catalog
import { chromium } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = [...fs.readdirSync(path.join(ROOT, 'src')).filter(f => f.endsWith('.js')).map(f => 'src/' + f), ...fs.readdirSync(path.join(ROOT, 'src/objects')).map(f => 'src/objects/' + f)];
const text = Object.fromEntries(src.map(f => [f, fs.readFileSync(path.join(ROOT, f), 'utf8')]));
// where an object is defined: its key:'…' property, a namedStar('…' call, or a ['…', 'Name' table row, in that order
const fileOf = key => src.find(f => text[f].includes(`key:'${key}'`)) || src.find(f => text[f].includes(`namedStar('${key}'`)) || src.find(f => new RegExp(`[\\[(]'${key}', '[A-Z]`).test(text[f])) || src.find(f => new RegExp(`key:\\s*'${key}'|'${key}'\\s*:\\s*\\{`).test(text[f])) || src.find(f => text[f].includes(`key:'${key.slice(0, -1)}' +`)) || '';
const browser = await chromium.launch({ args:['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage();
await page.addInitScript(() => { window.__noAdapt = true; });
await page.goto('file://' + path.join(ROOT, 'dist', 'index.html'));
await page.waitForFunction(() => window.__cosmos && window.__cosmos.OBJ);
const rows = await page.evaluate(() => {
  const c = window.__cosmos, LY = 9.4607e12, earth = c.BYKEY.earth;
  const size = o => o.isBH || (o.prog && o.prog === c.BYKEY.sgra.prog) ? o.rad/20 : (o.sizeR || (o.starR ? o.starR*o.rad : o.rad*(o.solid || 0.6)));
  return c.OBJ.filter(o => !o.marker && o.atlas !== false && o.group).map(o => ({
    key:o.key, name:o.name, group:o.group, type:o.type, bh:!!(o.isBH || (o.prog && o.prog === c.BYKEY.sgra.prog)),
    distLy:o.distNow ? o.distNow() : Math.hypot(o.pos[0] - earth.pos[0], o.pos[1] - earth.pos[1], o.pos[2] - earth.pos[2]), sizeKm:2*size(o)*LY,
    views:(o.views || []).length, flyby:!!o.flyby, tour:c.TOUR.includes(o.index) }));
});
await browser.close();
for (const r of rows) r.file = fileOf(r.key);
const fmtD = ly => ly < 0.02 ? Math.round(ly*9.4607e12).toLocaleString('en-US') + ' km' : ly < 1e6 ? (+ly.toPrecision(3)).toLocaleString('en-US') + ' ly' : (+(ly/1e6).toPrecision(3)) + ' Mly';
const fmtS = km => km < 1 ? Math.round(km*1000) + ' m' : km < 1e7 ? Math.round(km).toLocaleString('en-US') + ' km' : (+(km/9.4607e12).toPrecision(3)).toLocaleString('en-US') + ' ly';
const GROUPS = { solar:'Solar System', comets:'Comets & meteors', stars:'Stars & stellar remnants', nebulae:'Nebulae & star clusters', galaxies:'Galaxies & black holes', cosmic:'The large-scale universe', travel:'Travellers' };
let md = `# Catalogue of implemented objects\n\nGenerated by \`npm run catalog\` from the built page on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.\n\n**${rows.length} objects** · ${rows.filter(r => r.bh).length} black holes · ${rows.filter(r => r.flyby).length} with flybys · ${rows.filter(r => r.tour).length} on the grand tour\n`;
for (const [g, title] of Object.entries(GROUPS)){
  const list = rows.filter(r => r.group === g).sort((a, b) => a.distLy - b.distLy); if (!list.length) continue;
  md += `\n## ${title} (${list.length})\n\n| key | name | distance | size | views | flyby | tour | file |\n| --- | --- | --- | --- | --- | --- | --- | --- |\n`;
  for (const r of list) md += `| \`${r.key}\` | ${r.name} | ${fmtD(r.distLy)} | ${fmtS(r.sizeKm)} | ${r.views} | ${r.flyby ? 'yes' : ''} | ${r.tour ? 'yes' : ''} | ${r.file} |\n`;
}
fs.writeFileSync(path.join(ROOT, 'docs', 'CATALOG.md'), md);
fs.writeFileSync(path.join(ROOT, 'docs', 'catalog.json'), JSON.stringify(rows, null, 1));
console.log(`docs/CATALOG.md: ${rows.length} objects`);
