// builds src/05l-lights.js: Earth's city lights at night from NASA's Black Marble 2016 (public domain, NASA Earth Observatory / Suomi NPP VIIRS),
// as an equirectangular grayscale PNG the Earth shader samples on the night side (uTex2).
// The source image is downloaded once into tools/cache/ (not committed):
//   https://eoimages.gsfc.nasa.gov/images/imagerecords/144000/144898/BlackMarble_2016_3km.jpg  (13500 x 6750, 8 MB)
// Usage (from the repo root, needs sharp from the root dev dependencies): node tools/earth-lights.mjs [width]
import sharp from 'sharp';
import fs from 'node:fs';
const SRC = 'tools/cache/BlackMarble_2016_3km.jpg', W = +(process.argv[2] || 2048), H = W/2;
if (!fs.existsSync(SRC)){ console.error('download the source first: see the comment at the top of this file'); process.exit(1); }
// shrink the colour map first (area averaging), then separate the lights: the map shows dark land and ocean in blue (blue about
// twice the red) and lights in yellow to white, so min(R, G) - 0.55 B is 0 for ocean, deserts and ice and near 1 for city cores
const data = await sharp(SRC, { limitInputPixels:false }).resize(W, H, { kernel:'lanczos3' }).removeAlpha().raw().toBuffer();
const small = Buffer.alloc(W*H);
for (let i=0, j=0; j<small.length; i+=3, j++){ const v = Math.max(0, Math.min((Math.min(data[i], data[i + 1]) - 0.55*data[i + 2] - 4)/115, 1));
  small[j] = Math.round(255*Math.pow(v, 0.72)); }   // (lift the dim end: small towns fade when averaged with dark neighbours)
const png = await sharp(small, { raw:{ width:W, height:H, channels:1 } }).png({ compressionLevel:9, palette:false }).toBuffer();
fs.writeFileSync('src/05l-lights.js', `// generated by tools/earth-lights.mjs: city lights at night, NASA Black Marble 2016 (public domain), ${W} x ${H} equirectangular, grayscale\nconst LIGHTS_PNG = 'data:image/png;base64,${png.toString('base64')}';\n`);
if (process.argv.includes('--preview')) fs.writeFileSync('tests/out/lights-preview.png', png);
console.log('lights', W + 'x' + H, (png.length/1024).toFixed(0) + ' KB png', '->', (png.length*4/3/1024).toFixed(0) + ' KB in the page');
